name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 'build-and-push'
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Generate SHA
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT
    
    - name: Login into the container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          romualdosantos/nlw.journey.api:${{ steps.generate_sha.outputs.sha }}
          romualdosantos/nlw.journey.api:latest